#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : FreeCAD
Version  : 0.19.2
Release  : 28
URL      : https://github.com/FreeCAD/FreeCAD/archive/0.19.2/FreeCAD-0.19.2.tar.gz
Source0  : https://github.com/FreeCAD/FreeCAD/archive/0.19.2/FreeCAD-0.19.2.tar.gz
Summary  : The Orocos Kinematics and Dynamics Library
Group    : Development/Tools
License  : Artistic-2.0 BSD-3-Clause CC-BY-SA-3.0 GPL-2.0 GPL-3.0 LGPL-2.1
Requires: Markdown
Requires: matplotlib
Requires: six
BuildRequires : Coin-dev
BuildRequires : Markdown
BuildRequires : OpenCASCADE
BuildRequires : OpenCASCADE-dev
BuildRequires : VTK-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : curl-dev
BuildRequires : double-conversion-dev
BuildRequires : doxygen
BuildRequires : eigen-data
BuildRequires : eigen-dev
BuildRequires : freetype-dev
BuildRequires : glew-dev
BuildRequires : glu-dev
BuildRequires : graphviz
BuildRequires : hdf5-dev
BuildRequires : libMED-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : libspnav-dev
BuildRequires : lz4-dev
BuildRequires : matplotlib
BuildRequires : mesa-dev
BuildRequires : openmpi-dev
BuildRequires : openssl-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(icu-uc)
BuildRequires : pybind11-python3
BuildRequires : pyside2-setup
BuildRequires : pyside2-setup-dev
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : qtbase-dev
BuildRequires : qtsvg-dev
BuildRequires : qttools-dev
BuildRequires : qtwebengine-dev
BuildRequires : qtx11extras-dev
BuildRequires : qtxmlpatterns-dev
BuildRequires : six
BuildRequires : swig
BuildRequires : xerces-c-dev
BuildRequires : xz-dev
BuildRequires : zlib-dev
Patch1: 0001-Python-3.10-compat.patch
Patch2: 0002-Make-smesh-compile-with-vtk9.patch

%description
To build FreeCAD on trusty/xenial using vagrant please copy either Vagrantfile.trusty/Vagrantfile.xenial to Vagrantfile then kick from this directory vagrant up. Go have a drink compilation can be very long
Build results are kept into the vm, use vagrant ssh to connect to it and go into Results directory where you will get your deb and snap files

%prep
%setup -q -n FreeCAD-0.19.2
cd %{_builddir}/FreeCAD-0.19.2
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1637004833
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -Wno-dev \
-DOCC_INCLUDE_DIR=/usr/include/oce \
-DBUILD_QT5=on \
-DBOOST_LIBRARYDIR=/usr/lib64 \
-DCMAKE_INSTALL_DATADIR=/usr/share/freecad/data \
-DCMAKE_INSTALL_DOCDIR=/usr/share/doc/freecad/ \
-DFORCE_LIMITED_API=1
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1637004833
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/FreeCAD
cp %{_builddir}/FreeCAD-0.19.2/LICENSE %{buildroot}/usr/share/package-licenses/FreeCAD/208f2fb3798571ba86c2c981a572a524e176eabc
cp %{_builddir}/FreeCAD-0.19.2/data/License.txt %{buildroot}/usr/share/package-licenses/FreeCAD/60b9be515a54dc57989caafba6f0e44c60c4382c
cp %{_builddir}/FreeCAD-0.19.2/src/3rdParty/libkdtree/COPYING %{buildroot}/usr/share/package-licenses/FreeCAD/a379ff7c3f8108ad0712ea011d72223def07dbc3
cp %{_builddir}/FreeCAD-0.19.2/src/3rdParty/salomesmesh/LICENCE.lgpl.txt %{buildroot}/usr/share/package-licenses/FreeCAD/8f1a637d2e2ed1bdb9eb01a7dccb5c12cc0557e1
cp %{_builddir}/FreeCAD-0.19.2/src/CXX/COPYRIGHT %{buildroot}/usr/share/package-licenses/FreeCAD/ca1cd5e4044f4b56625ab1cf18481eb2fb238c44
cp %{_builddir}/FreeCAD-0.19.2/src/Mod/Path/libarea/kurve/License.txt %{buildroot}/usr/share/package-licenses/FreeCAD/3d2d68eddf055ae73e88855b3b00af67dc7b16ed
cp %{_builddir}/FreeCAD-0.19.2/src/Mod/TechDraw/Gui/Resources/fonts/osifont.license %{buildroot}/usr/share/package-licenses/FreeCAD/0cf06d4046ebebbe057779123ffc6ceac69785f3
cp %{_builddir}/FreeCAD-0.19.2/vagrant/Xenial/bin/license.txt %{buildroot}/usr/share/package-licenses/FreeCAD/53011bda6ec50e2a39858d6e4b3bea1197134fe1
cp %{_builddir}/FreeCAD-0.19.2/vagrant/bin/license.txt %{buildroot}/usr/share/package-licenses/FreeCAD/53011bda6ec50e2a39858d6e4b3bea1197134fe1
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
