#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : FreeCAD
Version  : 0.18.5
Release  : 26
URL      : https://github.com/FreeCAD/FreeCAD/archive/0.18.5/FreeCAD-0.18.5.tar.gz
Source0  : https://github.com/FreeCAD/FreeCAD/archive/0.18.5/FreeCAD-0.18.5.tar.gz
Summary  : Python Lex & Yacc
Group    : Development/Tools
License  : Artistic-2.0 BSD-3-Clause CC-BY-SA-3.0 GPL-2.0 GPL-3.0 LGPL-2.1
Requires: FreeCAD-bin = %{version}-%{release}
Requires: FreeCAD-data = %{version}-%{release}
Requires: FreeCAD-lib = %{version}-%{release}
Requires: FreeCAD-license = %{version}-%{release}
Requires: matplotlib
Requires: six
BuildRequires : Coin-dev
BuildRequires : OpenCASCADE
BuildRequires : OpenCASCADE-dev
BuildRequires : VTK-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-kde
BuildRequires : double-conversion-dev
BuildRequires : doxygen
BuildRequires : eigen-data
BuildRequires : eigen-dev
BuildRequires : freetype-dev
BuildRequires : glew-dev
BuildRequires : glu-dev
BuildRequires : graphviz
BuildRequires : hdf5-dev
BuildRequires : libMED-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : libspnav-dev
BuildRequires : lz4-dev
BuildRequires : matplotlib
BuildRequires : mesa-dev
BuildRequires : openmpi-dev
BuildRequires : pkg-config
BuildRequires : pybind11-python3
BuildRequires : pyside2-setup
BuildRequires : pyside2-setup-dev
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : qtbase-dev
BuildRequires : qtsvg-dev
BuildRequires : qttools-dev
BuildRequires : qtx11extras-dev
BuildRequires : six
BuildRequires : swig
BuildRequires : xerces-c-dev
BuildRequires : xz-dev
BuildRequires : zlib-dev
Patch1: python3.patch
Patch2: 0001-Workaround-for-py3.8-compat-fix-merged-upstream.patch
Patch3: 0002-Update-FindPySide2Tools-for-PySide2-5.14-issue-4229.patch
Patch4: 0003-Fix-build-with-python-3.9.patch
Patch5: 0004-Fix-build-with-Qt-5.15-and-newer.patch
Patch6: 0005-Fix-qt5-5.15.0-build.patch
Patch7: 0006-boost-use-global-placeholders.patch
Patch8: 0007-Add-some-missing-boost-headers.patch
Patch9: 0008-Make-smesh-compile-with-vtk9.patch

%description
PLY is yet another implementation of lex and yacc for Python. Some notable
        features include the fact that its implemented entirely in Python and it
        uses LALR(1) parsing which is efficient and well suited for larger grammars.
        
        PLY provides most of the standard lex/yacc features including support for empty 
        productions, precedence rules, error recovery, and support for ambiguous grammars. 
        
        PLY is extremely easy to use and provides very extensive error checking. 
        It is compatible with both Python 2 and Python 3.

%package bin
Summary: bin components for the FreeCAD package.
Group: Binaries
Requires: FreeCAD-data = %{version}-%{release}
Requires: FreeCAD-license = %{version}-%{release}

%description bin
bin components for the FreeCAD package.


%package data
Summary: data components for the FreeCAD package.
Group: Data

%description data
data components for the FreeCAD package.


%package doc
Summary: doc components for the FreeCAD package.
Group: Documentation

%description doc
doc components for the FreeCAD package.


%package lib
Summary: lib components for the FreeCAD package.
Group: Libraries
Requires: FreeCAD-data = %{version}-%{release}
Requires: FreeCAD-license = %{version}-%{release}

%description lib
lib components for the FreeCAD package.


%package license
Summary: license components for the FreeCAD package.
Group: Default

%description license
license components for the FreeCAD package.


%prep
%setup -q -n FreeCAD-0.18.5
cd %{_builddir}/FreeCAD-0.18.5
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1
%patch8 -p1
%patch9 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1614022238
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -Wno-dev \
-DOCC_INCLUDE_DIR=/usr/include/oce \
-DBUILD_QT5=on \
-DBOOST_LIBRARYDIR=/usr/lib64 \
-DCMAKE_INSTALL_DATADIR=/usr/share/freecad/data \
-DCMAKE_INSTALL_DOCDIR=/usr/share/doc/freecad/
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1614022238
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/FreeCAD
cp %{_builddir}/FreeCAD-0.18.5/LICENSE %{buildroot}/usr/share/package-licenses/FreeCAD/208f2fb3798571ba86c2c981a572a524e176eabc
cp %{_builddir}/FreeCAD-0.18.5/data/License.txt %{buildroot}/usr/share/package-licenses/FreeCAD/60b9be515a54dc57989caafba6f0e44c60c4382c
cp %{_builddir}/FreeCAD-0.18.5/src/3rdParty/libkdtree/COPYING %{buildroot}/usr/share/package-licenses/FreeCAD/a379ff7c3f8108ad0712ea011d72223def07dbc3
cp %{_builddir}/FreeCAD-0.18.5/src/3rdParty/salomesmesh/LICENCE.lgpl.txt %{buildroot}/usr/share/package-licenses/FreeCAD/8f1a637d2e2ed1bdb9eb01a7dccb5c12cc0557e1
cp %{_builddir}/FreeCAD-0.18.5/src/CXX/COPYRIGHT %{buildroot}/usr/share/package-licenses/FreeCAD/ca1cd5e4044f4b56625ab1cf18481eb2fb238c44
cp %{_builddir}/FreeCAD-0.18.5/src/Mod/Idf/Idflibs/License.txt %{buildroot}/usr/share/package-licenses/FreeCAD/4b467e35d319b0a46dc3dc3013d1475bb4d4ec0c
cp %{_builddir}/FreeCAD-0.18.5/src/Mod/Path/libarea/kurve/License.txt %{buildroot}/usr/share/package-licenses/FreeCAD/3d2d68eddf055ae73e88855b3b00af67dc7b16ed
cp %{_builddir}/FreeCAD-0.18.5/src/Mod/TechDraw/Gui/Resources/fonts/osifont.license %{buildroot}/usr/share/package-licenses/FreeCAD/0cf06d4046ebebbe057779123ffc6ceac69785f3
cp %{_builddir}/FreeCAD-0.18.5/vagrant/Xenial/bin/license.txt %{buildroot}/usr/share/package-licenses/FreeCAD/53011bda6ec50e2a39858d6e4b3bea1197134fe1
cp %{_builddir}/FreeCAD-0.18.5/vagrant/bin/license.txt %{buildroot}/usr/share/package-licenses/FreeCAD/53011bda6ec50e2a39858d6e4b3bea1197134fe1
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/Ext/PySide/QtCore.py
/usr/Ext/PySide/QtGui.py
/usr/Ext/PySide/QtSvg.py
/usr/Ext/PySide/QtUiTools.py
/usr/Ext/PySide/__init__.py
/usr/Ext/freecad/__init__.py
/usr/Mod/AddonManager/AddonManager.py
/usr/Mod/AddonManager/AddonManagerGui.py
/usr/Mod/AddonManager/Init.py
/usr/Mod/AddonManager/InitGui.py
/usr/Mod/AddonManager/addonmanager_macro.py
/usr/Mod/AddonManager/addonmanager_utilities.py
/usr/Mod/Arch/Arch.py
/usr/Mod/Arch/ArchAxis.py
/usr/Mod/Arch/ArchBuilding.py
/usr/Mod/Arch/ArchBuildingPart.py
/usr/Mod/Arch/ArchCommands.py
/usr/Mod/Arch/ArchComponent.py
/usr/Mod/Arch/ArchCutPlane.py
/usr/Mod/Arch/ArchEquipment.py
/usr/Mod/Arch/ArchFloor.py
/usr/Mod/Arch/ArchFrame.py
/usr/Mod/Arch/ArchMaterial.py
/usr/Mod/Arch/ArchNesting.py
/usr/Mod/Arch/ArchPanel.py
/usr/Mod/Arch/ArchPipe.py
/usr/Mod/Arch/ArchPrecast.py
/usr/Mod/Arch/ArchProfile.py
/usr/Mod/Arch/ArchRebar.py
/usr/Mod/Arch/ArchReference.py
/usr/Mod/Arch/ArchRoof.py
/usr/Mod/Arch/ArchSchedule.py
/usr/Mod/Arch/ArchSectionPlane.py
/usr/Mod/Arch/ArchSite.py
/usr/Mod/Arch/ArchSpace.py
/usr/Mod/Arch/ArchStairs.py
/usr/Mod/Arch/ArchStructure.py
/usr/Mod/Arch/ArchVRM.py
/usr/Mod/Arch/ArchWall.py
/usr/Mod/Arch/ArchWindow.py
/usr/Mod/Arch/Arch_rc.py
/usr/Mod/Arch/Dice3DS/__init__.py
/usr/Mod/Arch/Dice3DS/dom3ds.py
/usr/Mod/Arch/Dice3DS/util.py
/usr/Mod/Arch/Init.py
/usr/Mod/Arch/InitGui.py
/usr/Mod/Arch/TestArch.py
/usr/Mod/Arch/import3DS.py
/usr/Mod/Arch/importDAE.py
/usr/Mod/Arch/importIFC.py
/usr/Mod/Arch/importIFClegacy.py
/usr/Mod/Arch/importJSON.py
/usr/Mod/Arch/importOBJ.py
/usr/Mod/Arch/importSH3D.py
/usr/Mod/Arch/importWebGL.py
/usr/Mod/Complete/Init.py
/usr/Mod/Complete/InitGui.py
/usr/Mod/Draft/Draft.py
/usr/Mod/Draft/DraftGeomUtils.py
/usr/Mod/Draft/DraftGui.py
/usr/Mod/Draft/DraftSnap.py
/usr/Mod/Draft/DraftTools.py
/usr/Mod/Draft/DraftTrackers.py
/usr/Mod/Draft/DraftVecUtils.py
/usr/Mod/Draft/Draft_rc.py
/usr/Mod/Draft/Init.py
/usr/Mod/Draft/InitGui.py
/usr/Mod/Draft/TestDraft.py
/usr/Mod/Draft/WorkingPlane.py
/usr/Mod/Draft/getSVG.py
/usr/Mod/Draft/importAirfoilDAT.py
/usr/Mod/Draft/importDWG.py
/usr/Mod/Draft/importDXF.py
/usr/Mod/Draft/importOCA.py
/usr/Mod/Draft/importSVG.py
/usr/Mod/Drawing/DrawingExample.py
/usr/Mod/Drawing/DrawingPatterns.py
/usr/Mod/Drawing/DrawingTests.py
/usr/Mod/Drawing/Init.py
/usr/Mod/Drawing/InitGui.py
/usr/Mod/Fem/Init.py
/usr/Mod/Fem/InitGui.py
/usr/Mod/Fem/ObjectsFem.py
/usr/Mod/Fem/Resources/ui/ElectrostaticPotential.ui
/usr/Mod/Fem/Resources/ui/ElementFluid1D.ui
/usr/Mod/Fem/Resources/ui/ElementGeometry1D.ui
/usr/Mod/Fem/Resources/ui/ElementGeometry2D.ui
/usr/Mod/Fem/Resources/ui/ElementRotation1D.ui
/usr/Mod/Fem/Resources/ui/FlowVelocity.ui
/usr/Mod/Fem/Resources/ui/InitialFlowVelocity.ui
/usr/Mod/Fem/Resources/ui/Material.ui
/usr/Mod/Fem/Resources/ui/MeshBoundaryLayer.ui
/usr/Mod/Fem/Resources/ui/MeshGmsh.ui
/usr/Mod/Fem/Resources/ui/MeshGroup.ui
/usr/Mod/Fem/Resources/ui/MeshGroupXDMFExport.ui
/usr/Mod/Fem/Resources/ui/MeshRegion.ui
/usr/Mod/Fem/Resources/ui/ResultShow.ui
/usr/Mod/Fem/Resources/ui/SolverCalculix.ui
/usr/Mod/Fem/TestFem.py
/usr/Mod/Fem/femcommands/__init__.py
/usr/Mod/Fem/femcommands/commands.py
/usr/Mod/Fem/femcommands/manager.py
/usr/Mod/Fem/femguiobjects/FemSelectionWidgets.py
/usr/Mod/Fem/femguiobjects/ViewProviderFemConstraint.py
/usr/Mod/Fem/femguiobjects/_TaskPanelFemSolverControl.py
/usr/Mod/Fem/femguiobjects/_ViewProviderFemConstraintBodyHeatSource.py
/usr/Mod/Fem/femguiobjects/_ViewProviderFemConstraintElectrostaticPotential.py
/usr/Mod/Fem/femguiobjects/_ViewProviderFemConstraintFlowVelocity.py
/usr/Mod/Fem/femguiobjects/_ViewProviderFemConstraintInitialFlowVelocity.py
/usr/Mod/Fem/femguiobjects/_ViewProviderFemConstraintSelfWeight.py
/usr/Mod/Fem/femguiobjects/_ViewProviderFemElementFluid1D.py
/usr/Mod/Fem/femguiobjects/_ViewProviderFemElementGeometry1D.py
/usr/Mod/Fem/femguiobjects/_ViewProviderFemElementGeometry2D.py
/usr/Mod/Fem/femguiobjects/_ViewProviderFemElementRotation1D.py
/usr/Mod/Fem/femguiobjects/_ViewProviderFemMaterial.py
/usr/Mod/Fem/femguiobjects/_ViewProviderFemMaterialMechanicalNonlinear.py
/usr/Mod/Fem/femguiobjects/_ViewProviderFemMeshBoundaryLayer.py
/usr/Mod/Fem/femguiobjects/_ViewProviderFemMeshGmsh.py
/usr/Mod/Fem/femguiobjects/_ViewProviderFemMeshGroup.py
/usr/Mod/Fem/femguiobjects/_ViewProviderFemMeshRegion.py
/usr/Mod/Fem/femguiobjects/_ViewProviderFemMeshResult.py
/usr/Mod/Fem/femguiobjects/_ViewProviderFemResultMechanical.py
/usr/Mod/Fem/femguiobjects/_ViewProviderFemSolverCalculix.py
/usr/Mod/Fem/femguiobjects/__init__.py
/usr/Mod/Fem/feminout/__init__.py
/usr/Mod/Fem/feminout/convert2TetGen.py
/usr/Mod/Fem/feminout/importCcxDatResults.py
/usr/Mod/Fem/feminout/importCcxFrdResults.py
/usr/Mod/Fem/feminout/importFenicsMesh.py
/usr/Mod/Fem/feminout/importInpMesh.py
/usr/Mod/Fem/feminout/importToolsFem.py
/usr/Mod/Fem/feminout/importVTKResults.py
/usr/Mod/Fem/feminout/importZ88Mesh.py
/usr/Mod/Fem/feminout/importZ88O2Results.py
/usr/Mod/Fem/feminout/readFenicsXDMF.py
/usr/Mod/Fem/feminout/readFenicsXML.py
/usr/Mod/Fem/feminout/writeFenicsXDMF.py
/usr/Mod/Fem/feminout/writeFenicsXML.py
/usr/Mod/Fem/femmesh/__init__.py
/usr/Mod/Fem/femmesh/femmesh2mesh.py
/usr/Mod/Fem/femmesh/gmshtools.py
/usr/Mod/Fem/femmesh/meshtools.py
/usr/Mod/Fem/femobjects/FemConstraint.py
/usr/Mod/Fem/femobjects/_FemConstraintBodyHeatSource.py
/usr/Mod/Fem/femobjects/_FemConstraintElectrostaticPotential.py
/usr/Mod/Fem/femobjects/_FemConstraintFlowVelocity.py
/usr/Mod/Fem/femobjects/_FemConstraintInitialFlowVelocity.py
/usr/Mod/Fem/femobjects/_FemConstraintSelfWeight.py
/usr/Mod/Fem/femobjects/_FemElementFluid1D.py
/usr/Mod/Fem/femobjects/_FemElementGeometry1D.py
/usr/Mod/Fem/femobjects/_FemElementGeometry2D.py
/usr/Mod/Fem/femobjects/_FemElementRotation1D.py
/usr/Mod/Fem/femobjects/_FemMaterial.py
/usr/Mod/Fem/femobjects/_FemMaterialMechanicalNonlinear.py
/usr/Mod/Fem/femobjects/_FemMeshBoundaryLayer.py
/usr/Mod/Fem/femobjects/_FemMeshGmsh.py
/usr/Mod/Fem/femobjects/_FemMeshGroup.py
/usr/Mod/Fem/femobjects/_FemMeshRegion.py
/usr/Mod/Fem/femobjects/_FemMeshResult.py
/usr/Mod/Fem/femobjects/_FemResultMechanical.py
/usr/Mod/Fem/femobjects/_FemSolverCalculix.py
/usr/Mod/Fem/femobjects/__init__.py
/usr/Mod/Fem/femresult/__init__.py
/usr/Mod/Fem/femresult/resulttools.py
/usr/Mod/Fem/femsolver/__init__.py
/usr/Mod/Fem/femsolver/calculix/__init__.py
/usr/Mod/Fem/femsolver/calculix/solver.py
/usr/Mod/Fem/femsolver/calculix/tasks.py
/usr/Mod/Fem/femsolver/calculix/writer.py
/usr/Mod/Fem/femsolver/elmer/__init__.py
/usr/Mod/Fem/femsolver/elmer/equations/__init__.py
/usr/Mod/Fem/femsolver/elmer/equations/elasticity.py
/usr/Mod/Fem/femsolver/elmer/equations/electrostatic.py
/usr/Mod/Fem/femsolver/elmer/equations/equation.py
/usr/Mod/Fem/femsolver/elmer/equations/flow.py
/usr/Mod/Fem/femsolver/elmer/equations/fluxsolver.py
/usr/Mod/Fem/femsolver/elmer/equations/heat.py
/usr/Mod/Fem/femsolver/elmer/equations/linear.py
/usr/Mod/Fem/femsolver/elmer/equations/nonlinear.py
/usr/Mod/Fem/femsolver/elmer/sifio.py
/usr/Mod/Fem/femsolver/elmer/solver.py
/usr/Mod/Fem/femsolver/elmer/tasks.py
/usr/Mod/Fem/femsolver/elmer/writer.py
/usr/Mod/Fem/femsolver/equationbase.py
/usr/Mod/Fem/femsolver/fenics/__init__.py
/usr/Mod/Fem/femsolver/fenics/fenics_tools.py
/usr/Mod/Fem/femsolver/report.py
/usr/Mod/Fem/femsolver/reportdialog.py
/usr/Mod/Fem/femsolver/run.py
/usr/Mod/Fem/femsolver/settings.py
/usr/Mod/Fem/femsolver/signal.py
/usr/Mod/Fem/femsolver/solverbase.py
/usr/Mod/Fem/femsolver/task.py
/usr/Mod/Fem/femsolver/writerbase.py
/usr/Mod/Fem/femsolver/z88/__init__.py
/usr/Mod/Fem/femsolver/z88/solver.py
/usr/Mod/Fem/femsolver/z88/tasks.py
/usr/Mod/Fem/femsolver/z88/writer.py
/usr/Mod/Fem/femtest/__init__.py
/usr/Mod/Fem/femtest/testccxtools.py
/usr/Mod/Fem/femtest/testcommon.py
/usr/Mod/Fem/femtest/testfiles/__init__.py
/usr/Mod/Fem/femtest/testfiles/ccx/Flow1D_mesh.py
/usr/Mod/Fem/femtest/testfiles/ccx/Flow1D_thermomech.FCStd
/usr/Mod/Fem/femtest/testfiles/ccx/Flow1D_thermomech.dat
/usr/Mod/Fem/femtest/testfiles/ccx/Flow1D_thermomech.frd
/usr/Mod/Fem/femtest/testfiles/ccx/Flow1D_thermomech.inp
/usr/Mod/Fem/femtest/testfiles/ccx/Flow1D_thermomech_expected_values
/usr/Mod/Fem/femtest/testfiles/ccx/Flow1D_thermomech_inout_nodes.txt
/usr/Mod/Fem/femtest/testfiles/ccx/__init__.py
/usr/Mod/Fem/femtest/testfiles/ccx/cube.FCStd
/usr/Mod/Fem/femtest/testfiles/ccx/cube_frequency.FCStd
/usr/Mod/Fem/femtest/testfiles/ccx/cube_frequency.dat
/usr/Mod/Fem/femtest/testfiles/ccx/cube_frequency.frd
/usr/Mod/Fem/femtest/testfiles/ccx/cube_frequency.inp
/usr/Mod/Fem/femtest/testfiles/ccx/cube_frequency_expected_values
/usr/Mod/Fem/femtest/testfiles/ccx/cube_mesh.py
/usr/Mod/Fem/femtest/testfiles/ccx/cube_static.FCStd
/usr/Mod/Fem/femtest/testfiles/ccx/cube_static.dat
/usr/Mod/Fem/femtest/testfiles/ccx/cube_static.frd
/usr/Mod/Fem/femtest/testfiles/ccx/cube_static.inp
/usr/Mod/Fem/femtest/testfiles/ccx/cube_static_expected_values
/usr/Mod/Fem/femtest/testfiles/ccx/multimat.inp
/usr/Mod/Fem/femtest/testfiles/ccx/multimat_mesh.py
/usr/Mod/Fem/femtest/testfiles/ccx/spine_mesh.py
/usr/Mod/Fem/femtest/testfiles/ccx/spine_thermomech.FCStd
/usr/Mod/Fem/femtest/testfiles/ccx/spine_thermomech.dat
/usr/Mod/Fem/femtest/testfiles/ccx/spine_thermomech.frd
/usr/Mod/Fem/femtest/testfiles/ccx/spine_thermomech.inp
/usr/Mod/Fem/femtest/testfiles/ccx/spine_thermomech_expected_values
/usr/Mod/Fem/femtest/testfiles/elmer/ELMERSOLVER_STARTINFO
/usr/Mod/Fem/femtest/testfiles/elmer/__init__.py
/usr/Mod/Fem/femtest/testfiles/elmer/case.sif
/usr/Mod/Fem/femtest/testfiles/elmer/group_mesh.geo
/usr/Mod/Fem/femtest/testfiles/mesh/__init__.py
/usr/Mod/Fem/femtest/testfiles/mesh/tetra10_mesh.inp
/usr/Mod/Fem/femtest/testfiles/mesh/tetra10_mesh.unv
/usr/Mod/Fem/femtest/testfiles/mesh/tetra10_mesh.vtk
/usr/Mod/Fem/femtest/testfiles/mesh/tetra10_mesh.z88
/usr/Mod/Fem/femtest/testmesh.py
/usr/Mod/Fem/femtest/testobject.py
/usr/Mod/Fem/femtest/testresult.py
/usr/Mod/Fem/femtest/testsolverframework.py
/usr/Mod/Fem/femtest/utilstest.py
/usr/Mod/Fem/femtools/__init__.py
/usr/Mod/Fem/femtools/ccxtools.py
/usr/Mod/Fem/femtools/femutils.py
/usr/Mod/Idf/Idf.py
/usr/Mod/Idf/Idflibs/0603_SMD.stp
/usr/Mod/Idf/Idflibs/0805_SMD.stp
/usr/Mod/Idf/Idflibs/1206_SMD.stp
/usr/Mod/Idf/Idflibs/1210_SMD.stp
/usr/Mod/Idf/Idflibs/1812_SMD.stp
/usr/Mod/Idf/Idflibs/2225_SMD.stp
/usr/Mod/Idf/Idflibs/2512_SMD.stp
/usr/Mod/Idf/Idflibs/CAP_50SGV_8_10.stp
/usr/Mod/Idf/Idflibs/EPL22_6_16.stp
/usr/Mod/Idf/Idflibs/I22_2_5_16.stp
/usr/Mod/Idf/Idflibs/I22_2_5_16withEPL22_6_16.stp
/usr/Mod/Idf/Idflibs/License.txt
/usr/Mod/Idf/Idflibs/MSOP_10.stp
/usr/Mod/Idf/Idflibs/RLF_12545.igs
/usr/Mod/Idf/Idflibs/RLF_12545.stp
/usr/Mod/Idf/Idflibs/RLF_7030.stp
/usr/Mod/Idf/Idflibs/SMB_DO_214AA.stp
/usr/Mod/Idf/Idflibs/SMC_DO_214AB.stp
/usr/Mod/Idf/Idflibs/SOD_323.igs
/usr/Mod/Idf/Idflibs/SOD_323.stp
/usr/Mod/Idf/Idflibs/SOD_523.stp
/usr/Mod/Idf/Idflibs/SOT23.igs
/usr/Mod/Idf/Idflibs/SOT23.stp
/usr/Mod/Idf/Idflibs/SOT404.igs
/usr/Mod/Idf/Idflibs/SOT404.stp
/usr/Mod/Idf/Idflibs/SOT428_DPAK.stp
/usr/Mod/Idf/Idflibs/SOT_323_3.stp
/usr/Mod/Idf/Idflibs/SOT_96.stp
/usr/Mod/Idf/Idflibs/TCMT1107_4.stp
/usr/Mod/Idf/Idflibs/TSM_103_01_L_DV_A.stp
/usr/Mod/Idf/Idflibs/TSM_104_01_L_DV_A.stp
/usr/Mod/Idf/Idflibs/TSS0P_8.stp
/usr/Mod/Idf/Idflibs/VC0603_SMD.stp
/usr/Mod/Idf/Idflibs/footprints_models.csv
/usr/Mod/Idf/Init.py
/usr/Mod/Image/ImageTools/_CommandImageScaling.py
/usr/Mod/Image/ImageTools/__init__.py
/usr/Mod/Image/Init.py
/usr/Mod/Image/InitGui.py
/usr/Mod/Import/Init.py
/usr/Mod/Import/InitGui.py
/usr/Mod/Import/gzip_utf8.py
/usr/Mod/Import/stepZ.py
/usr/Mod/Inspection/Init.py
/usr/Mod/Inspection/InitGui.py
/usr/Mod/Material/Init.py
/usr/Mod/Material/InitGui.py
/usr/Mod/Material/MatPropDict.xml
/usr/Mod/Material/Material.py
/usr/Mod/Material/MaterialEditor.py
/usr/Mod/Material/Material_rc.py
/usr/Mod/Material/importFCMat.py
/usr/Mod/Material/materials-editor.ui
/usr/Mod/Measure/Init.py
/usr/Mod/Mesh/BuildRegularGeoms.py
/usr/Mod/Mesh/Init.py
/usr/Mod/Mesh/InitGui.py
/usr/Mod/Mesh/MeshTestsApp.py
/usr/Mod/MeshPart/Init.py
/usr/Mod/MeshPart/InitGui.py
/usr/Mod/MeshPart/MeshFlatteningCommand.py
/usr/Mod/OpenSCAD/Init.py
/usr/Mod/OpenSCAD/InitGui.py
/usr/Mod/OpenSCAD/OpenSCAD2Dgeom.py
/usr/Mod/OpenSCAD/OpenSCADCommands.py
/usr/Mod/OpenSCAD/OpenSCADFeatures.py
/usr/Mod/OpenSCAD/OpenSCADUtils.py
/usr/Mod/OpenSCAD/OpenSCAD_rc.py
/usr/Mod/OpenSCAD/colorcodeshapes.py
/usr/Mod/OpenSCAD/expandplacements.py
/usr/Mod/OpenSCAD/exportCSG.py
/usr/Mod/OpenSCAD/importCSG.py
/usr/Mod/OpenSCAD/ply/README
/usr/Mod/OpenSCAD/ply/__init__.py
/usr/Mod/OpenSCAD/ply/lex.py
/usr/Mod/OpenSCAD/ply/yacc.py
/usr/Mod/OpenSCAD/replaceobj.py
/usr/Mod/OpenSCAD/tokrules.py
/usr/Mod/Part/AttachmentEditor/Commands.py
/usr/Mod/Part/AttachmentEditor/FrozenClass.py
/usr/Mod/Part/AttachmentEditor/TaskAttachmentEditor.py
/usr/Mod/Part/AttachmentEditor/TaskAttachmentEditor.ui
/usr/Mod/Part/AttachmentEditor/__init__.py
/usr/Mod/Part/BOPTools/GeneralFuseResult.py
/usr/Mod/Part/BOPTools/JoinAPI.py
/usr/Mod/Part/BOPTools/JoinFeatures.py
/usr/Mod/Part/BOPTools/ShapeMerge.py
/usr/Mod/Part/BOPTools/SplitAPI.py
/usr/Mod/Part/BOPTools/SplitFeatures.py
/usr/Mod/Part/BOPTools/Utils.py
/usr/Mod/Part/BOPTools/__init__.py
/usr/Mod/Part/BasicShapes/Shapes.py
/usr/Mod/Part/BasicShapes/__init__.py
/usr/Mod/Part/CompoundTools/CompoundFilter.py
/usr/Mod/Part/CompoundTools/Explode.py
/usr/Mod/Part/CompoundTools/_CommandCompoundFilter.py
/usr/Mod/Part/CompoundTools/_CommandExplodeCompound.py
/usr/Mod/Part/CompoundTools/__init__.py
/usr/Mod/Part/Init.py
/usr/Mod/Part/InitGui.py
/usr/Mod/Part/JoinFeatures.py
/usr/Mod/Part/MakeBottle.py
/usr/Mod/Part/TestPartApp.py
/usr/Mod/Part/TestPartGui.py
/usr/Mod/PartDesign/Init.py
/usr/Mod/PartDesign/InitGui.py
/usr/Mod/PartDesign/InvoluteGearFeature.py
/usr/Mod/PartDesign/InvoluteGearFeature.ui
/usr/Mod/PartDesign/PartDesignTests/TestBoolean.py
/usr/Mod/PartDesign/PartDesignTests/TestChamfer.py
/usr/Mod/PartDesign/PartDesignTests/TestDatum.py
/usr/Mod/PartDesign/PartDesignTests/TestDraft.py
/usr/Mod/PartDesign/PartDesignTests/TestFillet.py
/usr/Mod/PartDesign/PartDesignTests/TestHole.py
/usr/Mod/PartDesign/PartDesignTests/TestLinearPattern.py
/usr/Mod/PartDesign/PartDesignTests/TestLoft.py
/usr/Mod/PartDesign/PartDesignTests/TestMirrored.py
/usr/Mod/PartDesign/PartDesignTests/TestMultiTransform.py
/usr/Mod/PartDesign/PartDesignTests/TestPad.py
/usr/Mod/PartDesign/PartDesignTests/TestPipe.py
/usr/Mod/PartDesign/PartDesignTests/TestPocket.py
/usr/Mod/PartDesign/PartDesignTests/TestPolarPattern.py
/usr/Mod/PartDesign/PartDesignTests/TestPrimitive.py
/usr/Mod/PartDesign/PartDesignTests/TestRevolve.py
/usr/Mod/PartDesign/PartDesignTests/TestShapeBinder.py
/usr/Mod/PartDesign/PartDesignTests/TestThickness.py
/usr/Mod/PartDesign/PartDesignTests/__init__.py
/usr/Mod/PartDesign/Scripts/DistanceBolt.py
/usr/Mod/PartDesign/Scripts/Epitrochoid.py
/usr/Mod/PartDesign/Scripts/FilletArc.py
/usr/Mod/PartDesign/Scripts/Gear.py
/usr/Mod/PartDesign/Scripts/Parallelepiped.py
/usr/Mod/PartDesign/Scripts/RadialCopy.py
/usr/Mod/PartDesign/Scripts/Spring.py
/usr/Mod/PartDesign/Scripts/__init__.py
/usr/Mod/PartDesign/TestPartDesignApp.py
/usr/Mod/PartDesign/TestPartDesignGui.py
/usr/Mod/PartDesign/WizardShaft/SegmentFunction.py
/usr/Mod/PartDesign/WizardShaft/Shaft.py
/usr/Mod/PartDesign/WizardShaft/ShaftDiagram.py
/usr/Mod/PartDesign/WizardShaft/ShaftFeature.py
/usr/Mod/PartDesign/WizardShaft/WizardShaft.py
/usr/Mod/PartDesign/WizardShaft/WizardShaft.svg
/usr/Mod/PartDesign/WizardShaft/WizardShaftTable.py
/usr/Mod/PartDesign/WizardShaft/__init__.py
/usr/Mod/PartDesign/__init__.py
/usr/Mod/PartDesign/fcgear/__init__.py
/usr/Mod/PartDesign/fcgear/fcgear.py
/usr/Mod/PartDesign/fcgear/fcgeardialog.py
/usr/Mod/PartDesign/fcgear/involute.py
/usr/Mod/PartDesign/fcgear/svggear.py
/usr/Mod/Path/Images/Ops/chamfer.svg
/usr/Mod/Path/Images/Tools/drill.svg
/usr/Mod/Path/Images/Tools/endmill.svg
/usr/Mod/Path/Images/Tools/v-bit.svg
/usr/Mod/Path/Init.py
/usr/Mod/Path/InitGui.py
/usr/Mod/Path/PathCommands.py
/usr/Mod/Path/PathScripts/PathAdaptive.py
/usr/Mod/Path/PathScripts/PathAdaptiveGui.py
/usr/Mod/Path/PathScripts/PathAreaOp.py
/usr/Mod/Path/PathScripts/PathArray.py
/usr/Mod/Path/PathScripts/PathCircularHoleBase.py
/usr/Mod/Path/PathScripts/PathCircularHoleBaseGui.py
/usr/Mod/Path/PathScripts/PathCommands.py
/usr/Mod/Path/PathScripts/PathComment.py
/usr/Mod/Path/PathScripts/PathCopy.py
/usr/Mod/Path/PathScripts/PathCustom.py
/usr/Mod/Path/PathScripts/PathDeburr.py
/usr/Mod/Path/PathScripts/PathDeburrGui.py
/usr/Mod/Path/PathScripts/PathDressup.py
/usr/Mod/Path/PathScripts/PathDressupAxisMap.py
/usr/Mod/Path/PathScripts/PathDressupDogbone.py
/usr/Mod/Path/PathScripts/PathDressupDragknife.py
/usr/Mod/Path/PathScripts/PathDressupHoldingTags.py
/usr/Mod/Path/PathScripts/PathDressupLeadInOut.py
/usr/Mod/Path/PathScripts/PathDressupRampEntry.py
/usr/Mod/Path/PathScripts/PathDressupTag.py
/usr/Mod/Path/PathScripts/PathDressupTagGui.py
/usr/Mod/Path/PathScripts/PathDressupTagPreferences.py
/usr/Mod/Path/PathScripts/PathDrilling.py
/usr/Mod/Path/PathScripts/PathDrillingGui.py
/usr/Mod/Path/PathScripts/PathEngrave.py
/usr/Mod/Path/PathScripts/PathEngraveBase.py
/usr/Mod/Path/PathScripts/PathEngraveGui.py
/usr/Mod/Path/PathScripts/PathFixture.py
/usr/Mod/Path/PathScripts/PathGeom.py
/usr/Mod/Path/PathScripts/PathGetPoint.py
/usr/Mod/Path/PathScripts/PathGui.py
/usr/Mod/Path/PathScripts/PathGuiInit.py
/usr/Mod/Path/PathScripts/PathHelix.py
/usr/Mod/Path/PathScripts/PathHelixGui.py
/usr/Mod/Path/PathScripts/PathHop.py
/usr/Mod/Path/PathScripts/PathIconViewProvider.py
/usr/Mod/Path/PathScripts/PathInspect.py
/usr/Mod/Path/PathScripts/PathJob.py
/usr/Mod/Path/PathScripts/PathJobCmd.py
/usr/Mod/Path/PathScripts/PathJobDlg.py
/usr/Mod/Path/PathScripts/PathJobGui.py
/usr/Mod/Path/PathScripts/PathLog.py
/usr/Mod/Path/PathScripts/PathMillFace.py
/usr/Mod/Path/PathScripts/PathMillFaceGui.py
/usr/Mod/Path/PathScripts/PathOp.py
/usr/Mod/Path/PathScripts/PathOpGui.py
/usr/Mod/Path/PathScripts/PathOpTools.py
/usr/Mod/Path/PathScripts/PathPocket.py
/usr/Mod/Path/PathScripts/PathPocketBase.py
/usr/Mod/Path/PathScripts/PathPocketBaseGui.py
/usr/Mod/Path/PathScripts/PathPocketGui.py
/usr/Mod/Path/PathScripts/PathPocketShape.py
/usr/Mod/Path/PathScripts/PathPocketShapeGui.py
/usr/Mod/Path/PathScripts/PathPost.py
/usr/Mod/Path/PathScripts/PathPostProcessor.py
/usr/Mod/Path/PathScripts/PathPreferences.py
/usr/Mod/Path/PathScripts/PathPreferencesPathDressup.py
/usr/Mod/Path/PathScripts/PathPreferencesPathJob.py
/usr/Mod/Path/PathScripts/PathProfileBase.py
/usr/Mod/Path/PathScripts/PathProfileBaseGui.py
/usr/Mod/Path/PathScripts/PathProfileContour.py
/usr/Mod/Path/PathScripts/PathProfileContourGui.py
/usr/Mod/Path/PathScripts/PathProfileEdges.py
/usr/Mod/Path/PathScripts/PathProfileEdgesGui.py
/usr/Mod/Path/PathScripts/PathProfileFaces.py
/usr/Mod/Path/PathScripts/PathProfileFacesGui.py
/usr/Mod/Path/PathScripts/PathSanity.py
/usr/Mod/Path/PathScripts/PathSelection.py
/usr/Mod/Path/PathScripts/PathSetupSheet.py
/usr/Mod/Path/PathScripts/PathSetupSheetGui.py
/usr/Mod/Path/PathScripts/PathSetupSheetOpPrototype.py
/usr/Mod/Path/PathScripts/PathSetupSheetOpPrototypeGui.py
/usr/Mod/Path/PathScripts/PathSimpleCopy.py
/usr/Mod/Path/PathScripts/PathSimulatorGui.py
/usr/Mod/Path/PathScripts/PathStock.py
/usr/Mod/Path/PathScripts/PathStop.py
/usr/Mod/Path/PathScripts/PathSurface.py
/usr/Mod/Path/PathScripts/PathSurfaceGui.py
/usr/Mod/Path/PathScripts/PathToolController.py
/usr/Mod/Path/PathScripts/PathToolEdit.py
/usr/Mod/Path/PathScripts/PathToolLibraryManager.py
/usr/Mod/Path/PathScripts/PathUtil.py
/usr/Mod/Path/PathScripts/PathUtils.py
/usr/Mod/Path/PathScripts/PostUtils.py
/usr/Mod/Path/PathScripts/__init__.py
/usr/Mod/Path/PathScripts/post/__init__.py
/usr/Mod/Path/PathScripts/post/centroid_post.py
/usr/Mod/Path/PathScripts/post/comparams_post.py
/usr/Mod/Path/PathScripts/post/dynapath_post.py
/usr/Mod/Path/PathScripts/post/example_pre.py
/usr/Mod/Path/PathScripts/post/grbl_G81_post.py
/usr/Mod/Path/PathScripts/post/grbl_post.py
/usr/Mod/Path/PathScripts/post/linuxcnc_post.py
/usr/Mod/Path/PathScripts/post/opensbp_post.py
/usr/Mod/Path/PathScripts/post/opensbp_pre.py
/usr/Mod/Path/PathScripts/post/philips_post.py
/usr/Mod/Path/PathScripts/post/rml_post.py
/usr/Mod/Path/PathScripts/post/slic3r_pre.py
/usr/Mod/Path/PathScripts/post/smoothie_post.py
/usr/Mod/Path/PathTests/PathTestUtils.py
/usr/Mod/Path/PathTests/TestPathCore.py
/usr/Mod/Path/PathTests/TestPathDeburr.py
/usr/Mod/Path/PathTests/TestPathDepthParams.py
/usr/Mod/Path/PathTests/TestPathDressupDogbone.py
/usr/Mod/Path/PathTests/TestPathDressupHoldingTags.py
/usr/Mod/Path/PathTests/TestPathGeom.py
/usr/Mod/Path/PathTests/TestPathLog.py
/usr/Mod/Path/PathTests/TestPathOpTools.py
/usr/Mod/Path/PathTests/TestPathPost.py
/usr/Mod/Path/PathTests/TestPathSetupSheet.py
/usr/Mod/Path/PathTests/TestPathStock.py
/usr/Mod/Path/PathTests/TestPathTool.py
/usr/Mod/Path/PathTests/TestPathToolController.py
/usr/Mod/Path/PathTests/TestPathTooltable.py
/usr/Mod/Path/PathTests/TestPathUtil.py
/usr/Mod/Path/PathTests/__init__.py
/usr/Mod/Path/PathTests/boxtest.fcstd
/usr/Mod/Path/PathTests/test_centroid_00.ngc
/usr/Mod/Path/PathTests/test_geomop.fcstd
/usr/Mod/Path/PathTests/test_linuxcnc_00.ngc
/usr/Mod/Path/TestPathApp.py
/usr/Mod/Plot/InitGui.py
/usr/Mod/Plot/Plot.py
/usr/Mod/Plot/PlotGui.py
/usr/Mod/Plot/Plot_rc.py
/usr/Mod/Plot/plotAxes/TaskPanel.py
/usr/Mod/Plot/plotAxes/TaskPanel.ui
/usr/Mod/Plot/plotAxes/__init__.py
/usr/Mod/Plot/plotLabels/TaskPanel.py
/usr/Mod/Plot/plotLabels/TaskPanel.ui
/usr/Mod/Plot/plotLabels/__init__.py
/usr/Mod/Plot/plotPositions/TaskPanel.py
/usr/Mod/Plot/plotPositions/TaskPanel.ui
/usr/Mod/Plot/plotPositions/__init__.py
/usr/Mod/Plot/plotSave/TaskPanel.py
/usr/Mod/Plot/plotSave/TaskPanel.ui
/usr/Mod/Plot/plotSave/__init__.py
/usr/Mod/Plot/plotSeries/TaskPanel.py
/usr/Mod/Plot/plotSeries/TaskPanel.ui
/usr/Mod/Plot/plotSeries/__init__.py
/usr/Mod/Plot/plotUtils/Paths.py
/usr/Mod/Plot/plotUtils/__init__.py
/usr/Mod/Points/Init.py
/usr/Mod/Points/InitGui.py
/usr/Mod/Raytracing/Init.py
/usr/Mod/Raytracing/InitGui.py
/usr/Mod/Raytracing/RaytracingExample.py
/usr/Mod/ReverseEngineering/Init.py
/usr/Mod/ReverseEngineering/InitGui.py
/usr/Mod/Robot/Init.py
/usr/Mod/Robot/InitGui.py
/usr/Mod/Robot/KukaExporter.py
/usr/Mod/Robot/MovieTool.py
/usr/Mod/Robot/RobotExample.py
/usr/Mod/Robot/RobotExampleTrajectoryOutOfShapes.py
/usr/Mod/Ship/InitGui.py
/usr/Mod/Ship/Instance.py
/usr/Mod/Ship/ShipGui.py
/usr/Mod/Ship/Ship_rc.py
/usr/Mod/Ship/TankInstance.py
/usr/Mod/Ship/WeightInstance.py
/usr/Mod/Ship/resources/examples/s60.fcstd
/usr/Mod/Ship/resources/examples/s60_katamaran.fcstd
/usr/Mod/Ship/resources/examples/wigley.fcstd
/usr/Mod/Ship/resources/examples/wigley_katamaran.fcstd
/usr/Mod/Ship/shipAreasCurve/PlotAux.py
/usr/Mod/Ship/shipAreasCurve/Preview.py
/usr/Mod/Ship/shipAreasCurve/TaskPanel.py
/usr/Mod/Ship/shipAreasCurve/TaskPanel.ui
/usr/Mod/Ship/shipAreasCurve/__init__.py
/usr/Mod/Ship/shipCapacityCurve/PlotAux.py
/usr/Mod/Ship/shipCapacityCurve/TaskPanel.py
/usr/Mod/Ship/shipCapacityCurve/TaskPanel.ui
/usr/Mod/Ship/shipCapacityCurve/Tools.py
/usr/Mod/Ship/shipCapacityCurve/__init__.py
/usr/Mod/Ship/shipCreateLoadCondition/Tools.py
/usr/Mod/Ship/shipCreateLoadCondition/__init__.py
/usr/Mod/Ship/shipCreateShip/Preview.py
/usr/Mod/Ship/shipCreateShip/TaskPanel.py
/usr/Mod/Ship/shipCreateShip/TaskPanel.ui
/usr/Mod/Ship/shipCreateShip/Tools.py
/usr/Mod/Ship/shipCreateShip/__init__.py
/usr/Mod/Ship/shipCreateTank/TaskPanel.py
/usr/Mod/Ship/shipCreateTank/TaskPanel.ui
/usr/Mod/Ship/shipCreateTank/Tools.py
/usr/Mod/Ship/shipCreateTank/__init__.py
/usr/Mod/Ship/shipCreateWeight/TaskPanel.py
/usr/Mod/Ship/shipCreateWeight/TaskPanel.ui
/usr/Mod/Ship/shipCreateWeight/Tools.py
/usr/Mod/Ship/shipCreateWeight/__init__.py
/usr/Mod/Ship/shipGZ/PlotAux.py
/usr/Mod/Ship/shipGZ/TaskPanel.py
/usr/Mod/Ship/shipGZ/TaskPanel.ui
/usr/Mod/Ship/shipGZ/Tools.py
/usr/Mod/Ship/shipGZ/__init__.py
/usr/Mod/Ship/shipHydrostatics/PlotAux.py
/usr/Mod/Ship/shipHydrostatics/TaskPanel.py
/usr/Mod/Ship/shipHydrostatics/TaskPanel.ui
/usr/Mod/Ship/shipHydrostatics/Tools.py
/usr/Mod/Ship/shipHydrostatics/__init__.py
/usr/Mod/Ship/shipLoadExample/TaskPanel.py
/usr/Mod/Ship/shipLoadExample/TaskPanel.ui
/usr/Mod/Ship/shipLoadExample/__init__.py
/usr/Mod/Ship/shipOutlineDraw/Preview.py
/usr/Mod/Ship/shipOutlineDraw/TaskPanel.py
/usr/Mod/Ship/shipOutlineDraw/TaskPanel.ui
/usr/Mod/Ship/shipOutlineDraw/__init__.py
/usr/Mod/Ship/shipUtils/Locale.py
/usr/Mod/Ship/shipUtils/Math.py
/usr/Mod/Ship/shipUtils/Paths.py
/usr/Mod/Ship/shipUtils/Units.py
/usr/Mod/Ship/shipUtils/__init__.py
/usr/Mod/Show/Containers.py
/usr/Mod/Show/DepGraphTools.py
/usr/Mod/Show/FrozenClass.py
/usr/Mod/Show/TempoVis.py
/usr/Mod/Show/__init__.py
/usr/Mod/Sketcher/Init.py
/usr/Mod/Sketcher/InitGui.py
/usr/Mod/Sketcher/ProfileLib/Hexagon.py
/usr/Mod/Sketcher/ProfileLib/RegularPolygon.py
/usr/Mod/Sketcher/ProfileLib/__init__.py
/usr/Mod/Sketcher/Profiles.py
/usr/Mod/Sketcher/SketcherExample.py
/usr/Mod/Sketcher/TestSketcherApp.py
/usr/Mod/Sketcher/TestSketcherGui.py
/usr/Mod/Spreadsheet/Init.py
/usr/Mod/Spreadsheet/InitGui.py
/usr/Mod/Spreadsheet/TestSpreadsheet.py
/usr/Mod/Spreadsheet/importXLSX.py
/usr/Mod/Start/Init.py
/usr/Mod/Start/InitGui.py
/usr/Mod/Start/StartPage/StartPage.py
/usr/Mod/Start/StartPage/TranslationTexts.py
/usr/Mod/Start/StartPage/__init__.py
/usr/Mod/Surface/Init.py
/usr/Mod/Surface/InitGui.py
/usr/Mod/TechDraw/Init.py
/usr/Mod/TechDraw/InitGui.py
/usr/Mod/TechDraw/TDTest/DHatchTest.py
/usr/Mod/TechDraw/TDTest/DProjGroupTest.py
/usr/Mod/TechDraw/TDTest/DVAnnoSymImageTest.py
/usr/Mod/TechDraw/TDTest/DVDimensionTest.py
/usr/Mod/TechDraw/TDTest/DVPartTest.py
/usr/Mod/TechDraw/TDTest/DVSectionTest.py
/usr/Mod/TechDraw/TDTest/TestHatch.svg
/usr/Mod/TechDraw/TDTest/TestImage.png
/usr/Mod/TechDraw/TDTest/TestSymbol.svg
/usr/Mod/TechDraw/TDTest/TestTemplate.svg
/usr/Mod/TechDraw/TDTest/__init__.py
/usr/Mod/TechDraw/TestTechDrawApp.py
/usr/Mod/Test/BaseTests.py
/usr/Mod/Test/Document.py
/usr/Mod/Test/Init.py
/usr/Mod/Test/InitGui.py
/usr/Mod/Test/Menu.py
/usr/Mod/Test/TestApp.py
/usr/Mod/Test/TestGui.py
/usr/Mod/Test/TestPythonSyntax.py
/usr/Mod/Test/UnicodeTests.py
/usr/Mod/Test/UnitTests.py
/usr/Mod/Test/Workbench.py
/usr/Mod/Test/__init__.py
/usr/Mod/Test/qtunittest.py
/usr/Mod/Test/testmakeWireString.py
/usr/Mod/Test/unittestgui.py
/usr/Mod/Tux/InitGui.py
/usr/Mod/Tux/NavigationIndicatorGui.py
/usr/Mod/Tux/PersistentToolbars.py
/usr/Mod/Tux/PersistentToolbarsGui.py
/usr/Mod/Tux/Tux_rc.py
/usr/Mod/Web/Init.py
/usr/Mod/Web/TestWebGui.py

%files bin
%defattr(-,root,root,-)
/usr/bin/FreeCAD
/usr/bin/FreeCADCmd

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.freecadweb.FreeCAD.desktop
/usr/share/freecad/data/Gui/Stylesheets/Dark-blue.qss
/usr/share/freecad/data/Gui/Stylesheets/Dark-green.qss
/usr/share/freecad/data/Gui/Stylesheets/Dark-orange.qss
/usr/share/freecad/data/Gui/Stylesheets/Light-blue.qss
/usr/share/freecad/data/Gui/Stylesheets/Light-green.qss
/usr/share/freecad/data/Gui/Stylesheets/Light-orange.qss
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/Hmovetoolbar_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/Hmovetoolbar_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/Hsepartoolbar_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/Hsepartoolbar_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/Vmovetoolbar_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/Vsepartoolbar_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/Vsepartoolbar_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/background_freecad.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/branch_end_closed_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/branch_end_closed_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/branch_end_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/branch_end_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/branch_end_open_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/branch_end_open_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/branch_more_closed_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/branch_more_closed_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/branch_more_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/branch_more_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/branch_more_open_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/branch_more_open_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/branch_vline_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/branch_vline_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/checkbox_indeterminate_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/checkbox_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/close_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/close_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/down_arrow_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/down_arrow_darker.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/down_arrow_disabled_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/down_arrow_disabled_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/down_arrow_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/down_arrow_lighter.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/left_arrow_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/left_arrow_darker.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/left_arrow_disabled_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/left_arrow_disabled_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/left_arrow_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/left_arrow_lighter.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/more_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/more_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/radiobutton_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/right_arrow_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/right_arrow_darker.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/right_arrow_disabled_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/right_arrow_disabled_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/right_arrow_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/right_arrow_lighter.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/sizegrip_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/sizegrip_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/splitter_horizontal_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/splitter_horizontal_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/splitter_vertical_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/splitter_vertical_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/transparent.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/undock_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/undock_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/up-down_arrow_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/up-down_arrow_darker.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/up-down_arrow_disabled_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/up-down_arrow_disabled_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/up-down_arrow_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/up-down_arrow_lighter.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/up_arrow_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/up_arrow_darker.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/up_arrow_disabled_dark.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/up_arrow_disabled_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/up_arrow_light.svg
/usr/share/freecad/data/Gui/Stylesheets/images_dark-light/up_arrow_lighter.svg
/usr/share/freecad/data/License.txt
/usr/share/freecad/data/Mod/Arch/Presets/profiles.csv
/usr/share/freecad/data/Mod/Arch/Presets/pset_definitions.csv
/usr/share/freecad/data/Mod/Arch/Resources/icons/ArchWorkbench.svg
/usr/share/freecad/data/Mod/Complete/Resources/icons/CompleteWorkbench.svg
/usr/share/freecad/data/Mod/Draft/Resources/icons/DraftWorkbench.svg
/usr/share/freecad/data/Mod/Drawing/Resources/icons/DrawingWorkbench.svg
/usr/share/freecad/data/Mod/Drawing/Templates/A0_Landscape_ISO7200.dxf
/usr/share/freecad/data/Mod/Drawing/Templates/A0_Landscape_ISO7200.svg
/usr/share/freecad/data/Mod/Drawing/Templates/A0_Landscape_plain.dxf
/usr/share/freecad/data/Mod/Drawing/Templates/A0_Landscape_plain.svg
/usr/share/freecad/data/Mod/Drawing/Templates/A0_Portrait_plain.dxf
/usr/share/freecad/data/Mod/Drawing/Templates/A0_Portrait_plain.svg
/usr/share/freecad/data/Mod/Drawing/Templates/A1_Landscape_ISO7200.dxf
/usr/share/freecad/data/Mod/Drawing/Templates/A1_Landscape_ISO7200.svg
/usr/share/freecad/data/Mod/Drawing/Templates/A1_Landscape_plain.dxf
/usr/share/freecad/data/Mod/Drawing/Templates/A1_Landscape_plain.svg
/usr/share/freecad/data/Mod/Drawing/Templates/A1_Portrait_plain.dxf
/usr/share/freecad/data/Mod/Drawing/Templates/A1_Portrait_plain.svg
/usr/share/freecad/data/Mod/Drawing/Templates/A2_Landscape_ISO7200.dxf
/usr/share/freecad/data/Mod/Drawing/Templates/A2_Landscape_ISO7200.svg
/usr/share/freecad/data/Mod/Drawing/Templates/A2_Landscape_plain.dxf
/usr/share/freecad/data/Mod/Drawing/Templates/A2_Landscape_plain.svg
/usr/share/freecad/data/Mod/Drawing/Templates/A2_Portrait_plain.dxf
/usr/share/freecad/data/Mod/Drawing/Templates/A2_Portrait_plain.svg
/usr/share/freecad/data/Mod/Drawing/Templates/A3_Landscape.dxf
/usr/share/freecad/data/Mod/Drawing/Templates/A3_Landscape.svg
/usr/share/freecad/data/Mod/Drawing/Templates/A3_Landscape_ISO7200.dxf
/usr/share/freecad/data/Mod/Drawing/Templates/A3_Landscape_ISO7200.svg
/usr/share/freecad/data/Mod/Drawing/Templates/A3_Landscape_plain.dxf
/usr/share/freecad/data/Mod/Drawing/Templates/A3_Landscape_plain.svg
/usr/share/freecad/data/Mod/Drawing/Templates/A3_Portrait_plain.dxf
/usr/share/freecad/data/Mod/Drawing/Templates/A3_Portrait_plain.svg
/usr/share/freecad/data/Mod/Drawing/Templates/A4_Landscape.dxf
/usr/share/freecad/data/Mod/Drawing/Templates/A4_Landscape.svg
/usr/share/freecad/data/Mod/Drawing/Templates/A4_Landscape_ISO7200.dxf
/usr/share/freecad/data/Mod/Drawing/Templates/A4_Landscape_ISO7200.svg
/usr/share/freecad/data/Mod/Drawing/Templates/A4_Landscape_plain.dxf
/usr/share/freecad/data/Mod/Drawing/Templates/A4_Landscape_plain.svg
/usr/share/freecad/data/Mod/Drawing/Templates/A4_Portrait_ISO7200.dxf
/usr/share/freecad/data/Mod/Drawing/Templates/A4_Portrait_ISO7200.svg
/usr/share/freecad/data/Mod/Drawing/Templates/A4_Portrait_plain.dxf
/usr/share/freecad/data/Mod/Drawing/Templates/A4_Portrait_plain.svg
/usr/share/freecad/data/Mod/Fem/Resources/icons/FemWorkbench.svg
/usr/share/freecad/data/Mod/Image/Resources/icons/ImageWorkbench.svg
/usr/share/freecad/data/Mod/Import/DxfPlate/blocks10.rub
/usr/share/freecad/data/Mod/Import/DxfPlate/blocks112.rub
/usr/share/freecad/data/Mod/Import/DxfPlate/blocks114.rub
/usr/share/freecad/data/Mod/Import/DxfPlate/classes14.rub
/usr/share/freecad/data/Mod/Import/DxfPlate/entities0.rub
/usr/share/freecad/data/Mod/Import/DxfPlate/entities12.rub
/usr/share/freecad/data/Mod/Import/DxfPlate/entities14.rub
/usr/share/freecad/data/Mod/Import/DxfPlate/header0.rub
/usr/share/freecad/data/Mod/Import/DxfPlate/header12.rub
/usr/share/freecad/data/Mod/Import/DxfPlate/header14.rub
/usr/share/freecad/data/Mod/Import/DxfPlate/objects14.rub
/usr/share/freecad/data/Mod/Import/DxfPlate/tables10.rub
/usr/share/freecad/data/Mod/Import/DxfPlate/tables112.rub
/usr/share/freecad/data/Mod/Import/DxfPlate/tables114.rub
/usr/share/freecad/data/Mod/Import/DxfPlate/tables20.rub
/usr/share/freecad/data/Mod/Import/DxfPlate/tables212.rub
/usr/share/freecad/data/Mod/Import/DxfPlate/tables214.rub
/usr/share/freecad/data/Mod/Inspection/Resources/icons/InspectionWorkbench.svg
/usr/share/freecad/data/Mod/Material/FluidMaterial/Air.FCMat
/usr/share/freecad/data/Mod/Material/FluidMaterial/None.FCMat
/usr/share/freecad/data/Mod/Material/FluidMaterial/Water.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/ABS-Generic.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Acrylic-Glass-Generic.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/AlMg3F24.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/AlMgSi1F31.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/AlZn4-5Mg1F35.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Aluminum-6061-T6.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/CalculiX-Steel.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Concrete-Generic.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Glass-E-GlassFibre.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Glass-Generic.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Glass-S2-GlassFibre.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/None.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/PA6-Generic.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/PET-Generic.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/PLA-Generic.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/PP-Generic.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/PTFE-Generic.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/PVC-Generic.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-15CrNi6.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-17CrNiMo6.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-1C22.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-1C35.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-1C45.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-1C60.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-20NiCrMo2.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-28Mn6.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-2C10.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-30CrNiMo8.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-34CrNiMo6.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-36CrNiMo4.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-36NiCrMo16.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-3C15.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-3C22.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-3C35.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-3V45.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-C10.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-C15.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-C22E.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-C25E.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-C30E.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-C40E.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-C50E.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-C55E.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-C60E.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-E295-GC.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-E295.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-E335-GC.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-E335.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-E360-GC.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-E360.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-EN-GJL-100.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-EN-GJL-150.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-EN-GJL-200.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-EN-GJL-250.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-EN-GJL-300.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-EN-GJL-350.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-EN-GJMB-350-10.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-EN-GJMB-550-4.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-EN-GJMB-650-2.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-EN-GJMW-350-4.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-EN-GJMW-360-12.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-EN-GJMW-400-5.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-EN-GJMW-450-7.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-EN-GJS-400-15.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-EN-GJS-500-7.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-EN-GJS-600-3.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-EN-GJS-700-2.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-EN-GJS-800-1.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-G16Mn5.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-G200.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-G20Mn5.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-G230.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-G260.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-G300.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-G30Mn5.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-Generic.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S185.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S235JO.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S235JR.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S235JRG1.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S260NC.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S275JO.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S275JR.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S275N.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S335JO.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S335JR.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S335N.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S340MC.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S355J2G3.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S380MC.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S420MC.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S420N.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S460MC.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S460N.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S500MC.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S550MC.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-S690MC.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-St-37-2K.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-St-E-255.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-St-E-315.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-St-E-380.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-St-E-460.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-St-E-500.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-X2CrNiMoN17-13-3.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-X2CrNiN24-4.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-X39CrMo17-1.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-X3CrNiMo13-14.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-X5CrNi18-10.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-X5CrNiMo17-12-2.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Steel-X6CrNiTi18-10.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/TEMPLATE.FCMat
/usr/share/freecad/data/Mod/Material/StandardMaterial/Wood-Generic.FCMat
/usr/share/freecad/data/Mod/Mesh/Resources/icons/MeshWorkbench.svg
/usr/share/freecad/data/Mod/OpenSCAD/Resources/icons/OpenSCADWorkbench.svg
/usr/share/freecad/data/Mod/Part/Resources/icons/PartWorkbench.svg
/usr/share/freecad/data/Mod/PartDesign/Resources/icons/PartDesignWorkbench.svg
/usr/share/freecad/data/Mod/Path/Resources/icons/PathWorkbench.svg
/usr/share/freecad/data/Mod/Plot/resources/icons/PlotWorkbench.svg
/usr/share/freecad/data/Mod/Points/Resources/icons/PointsWorkbench.svg
/usr/share/freecad/data/Mod/Raytracing/Resources/icons/RaytracingWorkbench.svg
/usr/share/freecad/data/Mod/Raytracing/Templates/LuxClassic.lxs
/usr/share/freecad/data/Mod/Raytracing/Templates/LuxOutdoor.lxs
/usr/share/freecad/data/Mod/Raytracing/Templates/ProjectStd.pov
/usr/share/freecad/data/Mod/Raytracing/Templates/RadiosityNormal.pov
/usr/share/freecad/data/Mod/Raytracing/Templates/RadiosityOutdoorHQ.pov
/usr/share/freecad/data/Mod/ReverseEngineering/Resources/icons/ReverseEngineeringWorkbench.svg
/usr/share/freecad/data/Mod/Robot/Lib/Kuka/kr125_3.wrl
/usr/share/freecad/data/Mod/Robot/Lib/Kuka/kr16.wrl
/usr/share/freecad/data/Mod/Robot/Lib/Kuka/kr210.WRL
/usr/share/freecad/data/Mod/Robot/Lib/Kuka/kr500_1.csv
/usr/share/freecad/data/Mod/Robot/Lib/Kuka/kr500_1.wrl
/usr/share/freecad/data/Mod/Robot/Lib/Kuka/kr_125.csv
/usr/share/freecad/data/Mod/Robot/Lib/Kuka/kr_16.csv
/usr/share/freecad/data/Mod/Robot/Lib/Kuka/kr_210_2.csv
/usr/share/freecad/data/Mod/Robot/Lib/Kuka/testprog.dat
/usr/share/freecad/data/Mod/Robot/Lib/Kuka/testprog.src
/usr/share/freecad/data/Mod/Robot/Resources/icons/RobotWorkbench.svg
/usr/share/freecad/data/Mod/Ship/resources/icons/ShipWorkbench.svg
/usr/share/freecad/data/Mod/Sketcher/Resources/icons/SketcherWorkbench.svg
/usr/share/freecad/data/Mod/Spreadsheet/Resources/icons/SpreadsheetWorkbench.svg
/usr/share/freecad/data/Mod/Start/Resources/icons/StartWorkbench.svg
/usr/share/freecad/data/Mod/Start/StartPage/EnableDownload.py
/usr/share/freecad/data/Mod/Start/StartPage/LoadCustom.py
/usr/share/freecad/data/Mod/Start/StartPage/LoadExample.py
/usr/share/freecad/data/Mod/Start/StartPage/LoadMRU.py
/usr/share/freecad/data/Mod/Start/StartPage/LoadNew.py
/usr/share/freecad/data/Mod/Start/StartPage/StartPage.css
/usr/share/freecad/data/Mod/Start/StartPage/StartPage.html
/usr/share/freecad/data/Mod/Start/StartPage/StartPage.js
/usr/share/freecad/data/Mod/Start/StartPage/images/developerhub.png
/usr/share/freecad/data/Mod/Start/StartPage/images/freecad.png
/usr/share/freecad/data/Mod/Start/StartPage/images/installed.png
/usr/share/freecad/data/Mod/Start/StartPage/images/manual.png
/usr/share/freecad/data/Mod/Start/StartPage/images/new_file_thumbnail.svg
/usr/share/freecad/data/Mod/Start/StartPage/images/poweruserhub.png
/usr/share/freecad/data/Mod/Start/StartPage/images/userhub.png
/usr/share/freecad/data/Mod/TechDraw/LineGroup/LineGroup.csv
/usr/share/freecad/data/Mod/TechDraw/PAT/FCPAT.pat
/usr/share/freecad/data/Mod/TechDraw/Patterns/brick01.svg
/usr/share/freecad/data/Mod/TechDraw/Patterns/concrete.svg
/usr/share/freecad/data/Mod/TechDraw/Patterns/cross.svg
/usr/share/freecad/data/Mod/TechDraw/Patterns/diagonal1.svg
/usr/share/freecad/data/Mod/TechDraw/Patterns/diagonal2.svg
/usr/share/freecad/data/Mod/TechDraw/Patterns/earth.svg
/usr/share/freecad/data/Mod/TechDraw/Patterns/hbone.svg
/usr/share/freecad/data/Mod/TechDraw/Patterns/line.svg
/usr/share/freecad/data/Mod/TechDraw/Patterns/plus.svg
/usr/share/freecad/data/Mod/TechDraw/Patterns/simple.svg
/usr/share/freecad/data/Mod/TechDraw/Patterns/solid.svg
/usr/share/freecad/data/Mod/TechDraw/Patterns/square.svg
/usr/share/freecad/data/Mod/TechDraw/Patterns/steel.svg
/usr/share/freecad/data/Mod/TechDraw/Patterns/wood.svg
/usr/share/freecad/data/Mod/TechDraw/Patterns/woodgrain.svg
/usr/share/freecad/data/Mod/TechDraw/Resources/fonts/osifont-lgpl3fe.ttf
/usr/share/freecad/data/Mod/TechDraw/Resources/fonts/osifont.license
/usr/share/freecad/data/Mod/TechDraw/Resources/icons/preferences-techdraw.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A0_Landscape_ISO7200TD.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A0_Landscape_ISO7200_Pep.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A0_Landscape_blank.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A1_Landscape_ISO7200TD.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A1_Landscape_ISO7200_Pep.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A1_Landscape_blank.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A2_Landscape_ISO7200TD.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A2_Landscape_ISO7200_Pep.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A2_Landscape_blank.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A3_LandscapeTD.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A3_Landscape_EN_m52.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A3_Landscape_FR_m52.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A3_Landscape_ISO7200TD.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A3_Landscape_ISO7200_Pep.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A3_Landscape_IT_m52.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A3_Landscape_blank.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A4_LandscapeTD.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A4_Landscape_ISO7200TD.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A4_Landscape_ISO7200_Pep.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A4_Landscape_blank.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A4_Portrait_ISO7200Pep.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A4_Portrait_ISO7200TD.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/A4_Portrait_blank.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/ANSIB.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/ANSIB_Portrait.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/HowToExample.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/USLetter_Landscape.svg
/usr/share/freecad/data/Mod/TechDraw/Templates/USLetter_Landscape_blank.svg
/usr/share/freecad/data/Mod/Test/Resources/icons/TestWorkbench.svg
/usr/share/freecad/data/examples/ArchDetail.FCStd
/usr/share/freecad/data/examples/DrawingExample.FCStd
/usr/share/freecad/data/examples/EngineBlock.FCStd
/usr/share/freecad/data/examples/FemCalculixCantilever2D.FCStd
/usr/share/freecad/data/examples/FemCalculixCantilever3D.FCStd
/usr/share/freecad/data/examples/FemCalculixCantilever3D_newSolver.FCStd
/usr/share/freecad/data/examples/PartDesignExample.FCStd
/usr/share/freecad/data/examples/RobotExample.FCStd
/usr/share/freecad/data/examples/Schenkel.stp
/usr/share/freecad/data/freecad-doc.png
/usr/share/freecad/data/freecad-icon-16.png
/usr/share/freecad/data/freecad-icon-32.png
/usr/share/freecad/data/freecad-icon-48.png
/usr/share/freecad/data/freecad-icon-64.png
/usr/share/freecad/data/freecad.svg
/usr/share/freecad/data/freecad.xpm
/usr/share/icons/hicolor/scalable/apps/org.freecadweb.FreeCAD.svg
/usr/share/metainfo/org.freecadweb.FreeCAD.appdata.xml
/usr/share/mime-packages/org.freecadweb.FreeCAD.xml

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/freecad/ThirdPartyLibraries.html
/usr/share/doc/freecad/freecad.qch
/usr/share/doc/freecad/freecad.qhc

%files lib
%defattr(-,root,root,-)
/usr/lib64/DraftUtils.so
/usr/lib64/Drawing.so
/usr/lib64/DrawingGui.so
/usr/lib64/Fem.so
/usr/lib64/FemGui.so
/usr/lib64/FreeCAD.so
/usr/lib64/FreeCADGui.so
/usr/lib64/Image.so
/usr/lib64/ImageGui.so
/usr/lib64/Import.so
/usr/lib64/ImportGui.so
/usr/lib64/Inspection.so
/usr/lib64/InspectionGui.so
/usr/lib64/Measure.so
/usr/lib64/Mesh.so
/usr/lib64/MeshGui.so
/usr/lib64/MeshPart.so
/usr/lib64/MeshPartGui.so
/usr/lib64/Part.so
/usr/lib64/PartDesignGui.so
/usr/lib64/PartGui.so
/usr/lib64/Path.so
/usr/lib64/PathGui.so
/usr/lib64/PathSimulator.so
/usr/lib64/Points.so
/usr/lib64/PointsGui.so
/usr/lib64/QtUnitGui.so
/usr/lib64/Raytracing.so
/usr/lib64/RaytracingGui.so
/usr/lib64/ReverseEngineering.so
/usr/lib64/ReverseEngineeringGui.so
/usr/lib64/Robot.so
/usr/lib64/RobotGui.so
/usr/lib64/Sketcher.so
/usr/lib64/SketcherGui.so
/usr/lib64/Spreadsheet.so
/usr/lib64/SpreadsheetGui.so
/usr/lib64/Start.so
/usr/lib64/StartGui.so
/usr/lib64/Surface.so
/usr/lib64/SurfaceGui.so
/usr/lib64/TechDraw.so
/usr/lib64/TechDrawGui.so
/usr/lib64/Web.so
/usr/lib64/_PartDesign.so
/usr/lib64/area.so
/usr/lib64/libDriver.so
/usr/lib64/libDriverDAT.so
/usr/lib64/libDriverSTL.so
/usr/lib64/libDriverUNV.so
/usr/lib64/libFreeCADApp.so
/usr/lib64/libFreeCADBase.so
/usr/lib64/libFreeCADGui.so
/usr/lib64/libMEFISTO2.so
/usr/lib64/libSMDS.so
/usr/lib64/libSMESH.so
/usr/lib64/libSMESHDS.so
/usr/lib64/libStdMeshers.so
/usr/lib64/libarea-native.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/FreeCAD/0cf06d4046ebebbe057779123ffc6ceac69785f3
/usr/share/package-licenses/FreeCAD/208f2fb3798571ba86c2c981a572a524e176eabc
/usr/share/package-licenses/FreeCAD/3d2d68eddf055ae73e88855b3b00af67dc7b16ed
/usr/share/package-licenses/FreeCAD/4b467e35d319b0a46dc3dc3013d1475bb4d4ec0c
/usr/share/package-licenses/FreeCAD/53011bda6ec50e2a39858d6e4b3bea1197134fe1
/usr/share/package-licenses/FreeCAD/60b9be515a54dc57989caafba6f0e44c60c4382c
/usr/share/package-licenses/FreeCAD/8f1a637d2e2ed1bdb9eb01a7dccb5c12cc0557e1
/usr/share/package-licenses/FreeCAD/a379ff7c3f8108ad0712ea011d72223def07dbc3
/usr/share/package-licenses/FreeCAD/ca1cd5e4044f4b56625ab1cf18481eb2fb238c44
